### ISSUE TITLE
Bug Report:import settings stop

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/GetMyIP#114] opened 2024-11-21 19:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues (both open and closed).

### What happened or didn't happen?

I repeated the import settings, after the third import the program does not restart.
I start program again, import again, program also not restarted.

### Steps To Reproduce

I repeated the import settings, after the third import the program does not restart.
I start program again, import again, program also not restarted.

### Version

 0.12.1.0

### Windows Version

Microsoft Windows 10.0.26100

**Comment by CMTriX** [comment] 2024-11-21 19:19
[GetMyIP.20241121.log](https://github.com/user-attachments/files/17850927/GetMyIP.20241121.log)

**Comment by Timthreetwelve** [comment] 2024-11-21 19:30
@CMTriX, I'll investigate and get back to you. Thanks for the log. 👍🏻

Tim

**Comment by Timthreetwelve** [comment] 2024-11-21 19:38
@CMTriX, Does the instance of GetMyIP that initiated the import actually shut down?

Tim

**Comment by CMTriX** [comment] 2024-11-21 19:46
Yes, it closed the first two times  , reloads. I restart program , import, it closes. It is not restarted, there is no other instance running. (taskview) it does not restart anymore. I do reboot now and test again.

**Comment by Timthreetwelve** [comment] 2024-11-21 19:50
Thanks.

**Comment by CMTriX** [comment] 2024-11-21 19:57
After reboot, i import. Program closing, does not restart. there is no other instance running. (taskview) .

**Comment by Timthreetwelve** [comment] 2024-11-21 20:07
Thanks, I don't see anything obvious. This may take me a while...

**Comment by Timthreetwelve** [comment] 2024-11-21 20:46
@CMTriX, I think I found it. Do you have the Minimize to tray instead of closing option checked? It's in Settings -> Tray Icon Settings.

**Comment by CMTriX** [comment] 2024-11-21 21:06
> @CMTriX, I think I found it. Do you have the Minimize to tray instead of closing option checked? It's in Settings -> Tray Icon Settings.

Yes.

**Comment by CMTriX** [comment] 2024-11-21 21:07
{
  "AutoRefresh": true,
  "AutoRefreshInterval": 1,
  "IncludeDebug": true,
  "IncludeV6": true,
  "InfoProvider": 0,
  "InitialPage": 1,
  "KeepOnTop": true,
  "LanguageTesting": false,
  "LogFile": "",
  "MapProvider": 1,
  "MinimizeToTray": true,
  "MinimizeToTrayOnClose": true,
  "NotifyOnIpChange": true,
  "ObfuscateLog": true,
  "PrimaryColor": 5,
  "RefreshAfterRestore": true,
  "SelectedFont": "Segoe UI",
  "RowSpacing": 1,
  "ShowExitInNav": true,
  "ShowHeader": false,
  "ShowASName": false,
  "ShowASNumber": false,
  "ShowCity": false,
  "ShowCountry": true,
  "ShowExternalIP": true,
  "ShowInternalIPv4": true,
  "ShowInternalIPv6": false,
  "ShowISP": false,
  "ShowIpVersion": false,
  "ShowOffset": false,
  "ShowLastRefresh": true,
  "ShowState": false,
  "ShowTimeZone": false,
  "StartCentered": true,
  "StartMinimized": false,
  "StartWithWindows": true,
  "TooltipHeading": "",
  "UILanguage": "en-US",
  "UISize": 3,
  "UITheme": 0,
  "UseOSLanguage": false,
  "WindowHeight": 575,
  "WindowLeft": 225,
  "WindowWidth": 830,
  "WindowTop": 58
}

**Comment by Timthreetwelve** [comment] 2024-11-21 21:16
That's preventing the running app from shutting down which in turn prevents the restart of another instance.

Working on a fix. 

Tim

**Comment by CMTriX** [comment] 2024-11-21 21:16
With  "MinimizeToTray": false,

Program first restarts on import, repeating import closes program, no restart.

**Comment by Timthreetwelve** [comment] 2024-11-21 21:22
Thanks for the update. 

Is the machine that you are running especially fast? Now I'm thinking that this may be a timing issue.

**Comment by Timthreetwelve** [comment] 2024-11-21 21:39
😲

That might be why I can't reproduce the problem on my tired old i5-10400. 

I believe that I'm going to rethink the restart process. Perhaps start another program that delays just a bit before restarting GetMyIP. Whatever I do, it won't happen before the end of the day.

Thanks for helping and for your patience.

Tim

**Comment by CMTriX** [comment] 2024-11-21 21:43
Np. I love bug hunting:p

I now go to bed! Goedenacht.

**Comment by Timthreetwelve** [comment] 2024-11-21 22:05
Or maybe I try to import without the need to restart.  Hmm...

**Comment by Timthreetwelve** [comment] 2024-11-22 04:01
I couldn't get the no restart method to work to my satisfaction.

I have a method that uses a powershell script that delays for a fraction of a second and then restarts GetmyIP. However it seems less than ideal.

I'm considering removing the restart and instead put up a message box that says something liek "import was successful, Please restart GetMyIP to complete the process". What would you think of that?

Now it's my turn to sleep.

**Comment by CMTriX** [comment] 2024-11-22 07:48
that is a good solution!

Nice dreams Tim-3-12!

**Comment by Timthreetwelve** [comment] 2024-11-22 22:42
@CMTriX, I just pushed the update.  There are two language changes, if you would be so kind...

```
    <!-- D | SettingsItem_ImportWarning -->  This is deleted
    <!-- A | MsgText_ImportSettingsRestart -->  This is added
```

I'll release this soon, but I want to give @bovirus and others time to make updates.

Tim

**Comment by CMTriX** [comment] 2024-11-23 09:43
<sys:String x:Key="MsgText_ImportSettingsRestart">Start Get My IP opnieuw om de geïmporteerde instellingen te gebruiken.</sys:String>

**Comment by Timthreetwelve** [comment] 2024-11-27 23:27
@CMTriX, Version 0.12.2 has been released. 

I'm going to add the Settings File export/import capabilities to my other apps. [TImVer](https://github.com/Timthreetwelve/TimVer) will be next, but I will be taking a couple of days off for the holiday. 🦃

Is "Black Friday" a thing over there?

Closing as completed.

Tim

**Comment by CMTriX** [comment] 2024-11-28 19:43
After extensive use and thorough testing I have unfortunately come to the conclusion that I have not found a new error. Too bad, really too bad.....

**Closed** 2024-11-28 19:44 UTC
Labels: bug

**Comment by Timthreetwelve** [comment] 2024-11-30 02:54
@CMTriX, thanks for your diligent testing. I might have to put you on the payroll. 🤣
