### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/GetMyIP#107] opened 2024-10-29 17:19 UTC
### Brief summary of your request

auto refresh at start

### Request details

I Would like to see a option in the program to initiate a refresh of the ip when the program is started and when opened if it is running on the background when clicking the tray icon/shortcut.

### Anything else?

Decorate my Xmass tree!

**Comment by Timthreetwelve** [comment] 2024-10-29 21:46
@CMTriX  To make sure that I understand your request, are you asking for the IP information to be refreshed when the GetMyIP window is shown after previously being minimized to the tray? 

Also, your request says:
> to initiate a refresh of the ip when the program is started

GetMyIP already refreshes the IP information when it starts. This makes me wonder if I'm not understanding this part of the request or if it's not working correctly. Please help me understand.


>Decorate my Xmass tree!

![tree](https://github.com/user-attachments/assets/35be94f4-dbfa-4ed8-ba0f-f0a852c7c8ce)
How's that?

**Comment by CMTriX** [comment] 2024-10-30 06:59
Hi Tim!
The auto refresh works fine.

- i set the refresh to example: 5 mins-
- minimize tool
- vpn changes the ip 
- i open  GetMYIP within 5 minutes after the change of ip
- old ip is showing
- i need to manual refresh

i would like to have a option when the application is started/being showed after recent minimized.


_The tree looks amazing!_

**Comment by Timthreetwelve** [comment] 2024-10-30 21:05
@CMTriX, I understand. I should have thought of that scenario, thanks for bringing it to my attention.

I've figured out most of the changes needed, so you can expect your request to be in the next version.

There will be some new strings to translate. I'll update this issue when I'm done updating en-US.  

Tim

**Comment by Timthreetwelve** [comment] 2024-11-04 21:22
I just pushed the latest en-US language additions to GitHub along with your enhancement. 

Tim

**Comment by CMTriX** [comment] 2024-11-10 07:34
Can you add the label REFRESHING/REFRESHED to the screen also, when the automatic refresh is done/running?
I checked the automatic refresh option, the program is in tray. I double click icon on desktop, but i don't see the auto refresh working. The old IP is still displayed. I also not see a refresh when i click the tray icon.

**Comment by Timthreetwelve** [comment] 2024-11-10 18:20
@CMTriX, I'm so sorry it's not working for you. Let's get the bug fixed and then add the label to the screen.

First, check the setting in the yellow box and see if it is checked.

![2024-11-10_12-07-43](https://github.com/user-attachments/assets/dc158e21-85e9-4ed6-9a14-48263daa04f6)

If it is checked, then copy the settings file `Ctrl+Shift+S`, and the log file `three-dot menu then View Log File` and either paste them into this issue or attach them to the issue, whichever is easiest for you.

Tim

**Comment by CMTriX** [comment] 2024-11-11 07:10
2024/11/11 08:04:54.28 INFO   GetMyIP (Get My IP) 0.11.3.0 is starting up
2024/11/11 08:04:54.30 INFO   GetMyIP © 2019 - 2024 Tim Kennedy
2024/11/11 08:04:54.30 DEBUG  GetMyIP Build date: woensdag 6 november 2024 19:56  (UTC)
2024/11/11 08:04:54.30 DEBUG  GetMyIP Commit ID: 0fc5ea5
2024/11/11 08:04:54.30 DEBUG  GetMyIP was started from C:\Users\AppData\Local\Programs\T_K\Get My IP\GetMyIP.exe
2024/11/11 08:04:54.30 DEBUG  GetMyIP Process ID: 6172
2024/11/11 08:04:54.30 DEBUG  Operating System version: Microsoft Windows 10.0.26100
2024/11/11 08:04:54.30 DEBUG  .NET version:  8.0.10
2024/11/11 08:04:54.30 DEBUG  Startup culture: nl-NL  UI: nl-NL
2024/11/11 08:04:54.30 DEBUG  Current culture: en-US  UI: en-US
2024/11/11 08:04:54.30 DEBUG  267 strings loaded from Languages/Strings.en-US.xaml
2024/11/11 08:04:54.58 DEBUG  Starting discovery of internal IP information.
2024/11/11 08:04:54.65 DEBUG  Starting discovery of external IP information.
2024/11/11 08:04:54.65 DEBUG  Connecting to: https://api.seeip.org
2024/11/11 08:04:54.67 DEBUG  Internal IPv4 Address is ###.###.#.#
2024/11/11 08:04:54.67 DEBUG  Internal IPv4 Address is ###.###.##.#
2024/11/11 08:04:54.67 DEBUG  Internal IPv4 Address is ###.###.###.#
2024/11/11 08:04:54.67 DEBUG  Internal IPv6 Address is XX##::###X:X###:###X:X#X#%##
2024/11/11 08:04:54.67 DEBUG  Internal IPv6 Address is #X##:X###:##X#:#:X#X#:#X#X:##X#:XX#X
2024/11/11 08:04:54.67 DEBUG  Internal IPv6 Address is #X##:X###:##X#:#:##XX:X###:XX#X:###X
2024/11/11 08:04:54.67 DEBUG  Internal IPv6 Address is XX##::####:X##X:X##X:#X##%#
2024/11/11 08:04:54.67 DEBUG  Internal IPv6 Address is XX##::X###:#X##:##X#:###%##
2024/11/11 08:04:54.67 DEBUG  Discovering internal addresses took 37.00 ms
2024/11/11 08:04:54.80 DEBUG  Refresh timer started. Refresh interval is 5 minutes
2024/11/11 08:04:55.12 DEBUG  Received status code: OK - OK from https://api.seeip.org
2024/11/11 08:04:55.12 DEBUG  Discovering external IP information took 471.45 ms
2024/11/11 08:04:55.12 DEBUG  External IP Address is #X##:X###:##X#:#:X#X#:#X#X:##X#:XX#X
2024/11/11 08:04:55.12 DEBUG  City is XXXXX
2024/11/11 08:04:55.12 DEBUG  State is XXXXXXXXX
2024/11/11 08:04:55.12 DEBUG  State is XX
2024/11/11 08:04:55.12 DEBUG  Country is XXXXXXXXXXX
2024/11/11 08:04:55.12 DEBUG  Country Code is XX
2024/11/11 08:04:55.12 DEBUG  Zip Code is ####
2024/11/11 08:04:55.12 DEBUG  Continent Code is XX
2024/11/11 08:04:55.12 DEBUG  Longitude is #.####
2024/11/11 08:04:55.12 DEBUG  Latitude is ##.####
2024/11/11 08:04:55.12 DEBUG  Time Zone is XXXXXX/XXXXXXXXX
2024/11/11 08:04:55.12 DEBUG  Offset from UTC is +##:##
2024/11/11 08:04:55.12 DEBUG  AS Number is ####
2024/11/11 08:04:55.12 DEBUG  Organization is XXX X.X.
2024/11/11 08:04:55.12 DEBUG  External IP information provider is XXXXX.XXX
2024/11/11 08:04:55.12 DEBUG  Tooltip is 62 bytes
2024/11/11 08:05:33.96 DEBUG  This instance of GetMyIP was activated because another instance attempted to start. 
2024/11/11 08:05:38.86 DEBUG  Refreshing IP information
2024/11/11 08:05:38.86 DEBUG  Starting discovery of internal IP information.
2024/11/11 08:05:38.96 DEBUG  Starting discovery of external IP information.
2024/11/11 08:05:38.96 DEBUG  Connecting to: https://api.seeip.org
2024/11/11 08:05:38.96 DEBUG  Internal IPv4 Address is ###.##.##.##
2024/11/11 08:05:38.96 DEBUG  Internal IPv4 Address is ###.###.#.#
2024/11/11 08:05:38.96 DEBUG  Internal IPv4 Address is ###.###.##.#
2024/11/11 08:05:38.96 DEBUG  Internal IPv4 Address is ###.###.###.#
2024/11/11 08:05:38.96 DEBUG  Internal IPv6 Address is XX##::###X:X###:###X:X#X#%##
2024/11/11 08:05:38.96 DEBUG  Internal IPv6 Address is #X##:X###:##X#:#:X#X#:#X#X:##X#:XX#X
2024/11/11 08:05:38.96 DEBUG  Internal IPv6 Address is #X##:X###:##X#:#:##XX:X###:XX#X:###X
2024/11/11 08:05:38.96 DEBUG  Internal IPv6 Address is XX##::####:X##X:X##X:#X##%#
2024/11/11 08:05:38.96 DEBUG  Internal IPv6 Address is XX##::X###:#X##:##X#:###%##
2024/11/11 08:05:38.96 DEBUG  Discovering internal addresses took 7.01 ms
2024/11/11 08:05:39.47 DEBUG  Received status code: OK - OK from https://api.seeip.org
2024/11/11 08:05:39.47 DEBUG  Discovering external IP information took 510.11 ms
2024/11/11 08:05:39.47 DEBUG  External IP Address is ##.###.###.###
2024/11/11 08:05:39.47 DEBUG  City is 
2024/11/11 08:05:39.47 DEBUG  State is 
2024/11/11 08:05:39.47 DEBUG  State is 
2024/11/11 08:05:39.47 DEBUG  Country is XXXXXXXXXXX
2024/11/11 08:05:39.47 DEBUG  Country Code is XX
2024/11/11 08:05:39.47 DEBUG  Zip Code is 
2024/11/11 08:05:39.47 DEBUG  Continent Code is XX
2024/11/11 08:05:39.47 DEBUG  Longitude is #.####
2024/11/11 08:05:39.47 DEBUG  Latitude is ##.####
2024/11/11 08:05:39.47 DEBUG  Time Zone is XXXXXX/XXXXXXXXX
2024/11/11 08:05:39.47 DEBUG  Offset from UTC is +##:##
2024/11/11 08:05:39.47 DEBUG  AS Number is #
2024/11/11 08:05:39.47 DEBUG  Organization is 
2024/11/11 08:05:39.47 DEBUG  External IP information provider is XXXXX.XXX
2024/11/11 08:05:39.47 DEBUG  Tooltip is 41 bytes
2024/11/11 08:07:43.35 DEBUG  This instance of GetMyIP was activated because another instance attempted to start. 
2024/11/11 08:08:20.87 DEBUG  Opening C:\Users\AppData\Local\Temp\T_K\GetMyIP.20241111.log in default application

**Comment by Timthreetwelve** [comment] 2024-11-11 18:43
Hmm, try opening Settings, then Language Settings, then click on the Open App Folder button.

File Explorer should open the application's folder. 

Open the `usersettings.json` with any text editor file and paste its contents here.

Thanks,
Tim

**Comment by CMTriX** [comment] 2024-11-11 18:52
{
  "AutoRefresh": true,
  "AutoRefreshInterval": 5,
  "IncludeDebug": true,
  "IncludeV6": true,
  "InfoProvider": 1,
  "InitialPage": 1,
  "KeepOnTop": true,
  "LanguageTesting": false,
  "LogFile": "",
  "MapProvider": 1,
  "MinimizeToTray": true,
  "MinimizeToTrayOnClose": true,
  "NotifyOnIpChange": true,
  "ObfuscateLog": true,
  "PrimaryColor": 5,
  "RefreshAfterRestore": true,
  "SelectedFont": "Segoe UI",
  "RowSpacing": 0,
  "ShowExitInNav": true,
  "ShowHeader": false,
  "ShowASName": false,
  "ShowASNumber": false,
  "ShowCity": false,
  "ShowCountry": true,
  "ShowExternalIP": true,
  "ShowInternalIPv4": true,
  "ShowInternalIPv6": false,
  "ShowISP": false,
  "ShowIpVersion": false,
  "ShowOffset": false,
  "ShowLastRefresh": true,
  "ShowState": false,
  "ShowTimeZone": false,
  "StartCentered": true,
  "StartMinimized": true,
  "StartWithWindows": true,
  "TooltipHeading": "",
  "UILanguage": "en-US",
  "UISize": 3,
  "UITheme": 2,
  "UseOSLanguage": false,
  "WindowHeight": 575,
  "WindowLeft": 1500,
  "WindowWidth": 830,
  "WindowTop": 590
}

**Comment by CMTriX** [comment] 2024-11-11 18:54
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "8.0.0"
      }
    ],
    "configProperties": {
      "MVVMTOOLKIT_ENABLE_INOTIFYPROPERTYCHANGING_SUPPORT": true,
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": true
    }
  }
}

**Comment by Timthreetwelve** [comment] 2024-11-11 22:33
@CMTriX, thanks for the settings file. It looks good.

Looking at the log file, I noticed that when the app started it says:

>2024/11/11 08:04:55.12 DEBUG External IP Address is #X##:X###:##X#:#:X#X#:#X#X:##X#:XX#X

I assume that you made a change to your network or VPN, because not a minute later is says:

>2024/11/11 08:05:39.47 DEBUG External IP Address is ##.###.###.###

Even though the addresses are obfuscated, we can tell that they are different. So, the app is aware that the external IP address has changed.

I also see in the log:

>2024/11/11 08:05:33.96 DEBUG This instance of GetMyIP was activated because another instance attempted to start.

This tells me that the app was not reopened from the tray icon, but that another instance of the app tried to start. GetMyIP is designed so that only one copy of the app can be active at a time. When a second copy tries to start it won't, it just switches to the first instance of the app, restoring it if it was minimized. Having said all of that, it should still update the IP information in the app and the tray icon. 

Would you try again, this time let the app minimize to the tray, change the IP address, and then restore it by clicking the tray icon?

Let me know if that has any effect on the IP address that is displayed, and if not, please paste the application log that contains those activities.

In the meantime, I will put the code under a microscope and see if something is keeping it from showing the updated IP address.

Thanks a lot for your help diagnosing this issue,

Tim

**Comment by CMTriX** [comment] 2024-11-12 07:19
Thank you. I will run some tests later this week step-by-step and drop the results here.

**Comment by Timthreetwelve** [comment] 2024-11-15 20:40
@CMTriX, I just wanted to give you a quick update and let you know that I'm still working on this.

Tim

**Comment by CMTriX** [comment] 2024-11-16 08:56
thnx for the update!

**Comment by Timthreetwelve** [comment] 2024-11-17 22:32
@CMTriX, I'm confident that I found the cause and have made changes to remedy the issue. The next update will include the fix.

I'll close this issue for now. It can be reopened if the issue reoccurs in the next update.

Tim

**Comment by CMTriX** [comment] 2024-11-18 10:03
Thank you!

**Comment by Timthreetwelve** [comment] 2024-11-20 18:36
@CMTriX, I was set to release an update when I found another bug with refreshing after restoring a minimized window. 

Reopening this issue.

Tim

**Closed** 2024-11-21 18:55 UTC
Labels: bug, enhancement
